export const tagPillarMapping = {
  'Mercado y Competencia': [
    'Competencia',
    'Industria Argentina',
    'Señales de Compra',
    'Estrategia Comercial',
    'Ventas B2B',
  ],
  'Plataforma y UX': [
    'Experiencia de Usuario',
    'Mantenimiento Web',
    'Prevención',
    'Rendimiento Web',
    'Seguridad',
    'SEO Técnico',
    'CRO',
    'Ecommerce',
  ],
  'Contenido y Autoridad': [
    'Autoridad de Marca',
    'LinkedIn',
    'Redes Sociales',
    'SEO',
    'Branding',
    'AEO',
    'Inteligencia Artificial',
  ],
  'Crecimiento y Adquisición': [
    'Estrategia Publicitaria',
    'Generación de Leads',
    'Google Ads',
    'Inteligencia de Datos',
    'Inversión',
    'Leads B2B',
    'Métricas',
    'Prospección B2B',
    'Ventas',
    'TV',
    'Publicidad Tradicional',
    'OOH',
    'DOOH',
    'Marketing Omnicanal',
    'Estrategia de Medios',
    'Publicidad Exterior',
  ],
  'Metodología y Estrategia': [
    'Agencia Digital',
    'Checklist',
    'Costo de Oportunidad',
    'Crecimiento',
    'Delegación',
    'Diagnóstico',
    'Estrategia',
    'Estrategia Digital',
    'Liderazgo',
    'Onboarding',
    'Partnership',
    'Proceso',
    'PyMEs',
    'Resultados',
    'ROI',
    'Sales Ops',
    'CRM',
    'Hubspot',
    'Automatización',
  ],
};
