export const tagPillarMapping = {
  'Mercado y Competencia': [
    'Competencia',
    'Industria Argentina',
    'Señales de Compra',
    'Estrategia Comercial',
  ],
  'Plataforma y UX': [
    'Experiencia de Usuario',
    'Mantenimiento Web',
    'Prevención',
    'Rendimiento Web',
    'Seguridad',
    'SEO Técnico',
  ],
  'Contenido y Autoridad': [
    'Autoridad de Marca',
    'LinkedIn',
    'Redes Sociales',
    'SEO',
  ],
  'Crecimiento y Adquisición': [
    'Estrategia Publicitaria',
    'Generación de Leads',
    'Google Ads',
    'Inteligencia de Datos',
    'Inversión',
    'Leads B2B',
    'Métricas',
    'Prospección B2B',
    'Ventas',
  ],
  'Metodología y Estrategia': [
    'Agencia Digital',
    'Checklist',
    'Costo de Oportunidad',
    'Crecimiento',
    'Delegación',
    'Diagnóstico',
    'Estrategia',
    'Estrategia Digital',
    'Liderazgo',
    'Onboarding',
    'Partnership',
    'Proceso',
    'PyMEs',
    'Resultados',
    'ROI',
  ],
};
